### ISSUE TITLE
Regras de documentação padrão

### ISSUE THREAD

**Issue by EmersonMiranda** [wilsade/WSPack#1]
Sugiro que a ferramenta WSPack já disponibilize algumas regras de documentação padrão para que sirvam de modelos (exemplos) para os usuários. 
Como exemplo já poderiam vir como padrão regras de documentações para tipos e membros já existentes no código como bool, sender, item entre outros.

**Comment by wilsade** [comment]
Emerson, boa tarde.
Com a criação do [wiki](https://github.com/wilsade/WSPack/wiki/Documenta%C3%A7%C3%A3o.Exemplos), acha necessário esta implementação?

**Comment by EmersonMiranda** [comment]
Não é necessário, boa tarde!

Em ter, 20 de nov de 2018 às 12:59, wilsade <notifications@github.com>
escreveu:
