### ISSUE TITLE
Strings no código

### ISSUE THREAD

**Issue by EmersonMiranda** [wilsade/WSPack#11]
Boa tarde!

Temos uma classe que possui um método que recebe uma "propertyName" e adiciona em uma lista de registros modificados.

método:
    public void RegisterModified(string propertyName)
    {
      if (AAlistModified.IndexOf(propertyName) == -1)
        AAlistModified.Add(propertyName);
    }

A utilização deste método é: 

Class XPTO
{
//...
    [Column]
    public string Nome
    {
      get { return _nome; }
      set
      {
        RegisterModified("Nome"); 
        _nome= value;
      }
    } private string _nome;
}

Gostaria de solicitar a inclusão deste método como Padrão desconsiderado para o Código de referência: RMSLocalizable02.

**Comment by wilsade** [comment]
Emerson, bom dia.
Esta funcionalidade não é do WSPack.
Favor abrir uma demanda para Engenharia para o EngPack.
Att,
