### ISSUE TITLE
Object reference ao gerar resource string

### ISSUE THREAD

**Issue by EmersonMiranda** [wilsade/WSPack#12]
A ferramenta sugeriu criar resource string para o string "rate" da linha de código abaixo

if (rate == -1)
      {
        throw new RMSValidateException(Resource.SCtrExceptionArgumentoInvalido, "rate");
      }

Porém ao utilizar a rotina de Gerar resource string foi retornado a mensagem de erro:
---------------------------
Microsoft Visual Studio
---------------------------
Object reference not set to an instance of an object.
---------------------------
OK   
---------------------------

**Comment by wilsade** [comment]
Não simulado
