### ISSUE TITLE
Error HRESULT E_FAIL ao gerar documentação

### ISSUE THREAD

**Issue by EmersonMiranda** [wilsade/WSPack#13]
Bom dia!

Ao utilizar o recurso de Gerar Documentação de código da ferramenta WS Pack, está sendo apresentado o erro:

---------------------------
Microsoft Visual Studio
---------------------------
Error HRESULT E_FAIL has been returned from a call to a COM component.
---------------------------
OK   
---------------------------

Esta mensagem foi apresentada ao gerar documentação do método abaixo Read do trecho de código abaixo:

  [Serializable]
  public class MovTMVParadigmaParams : RMSApplicationParamsBase
  {

    public static MovTMVParadigmaParams Read(int codColigada, string tipoMov)
    {
      return Read(codColigada, tipoMov, true);
    }....
}

**Comment by wilsade** [comment]
Feita a correção.
Disponível na próxima versão: 2.0.0.93 (ou superior)
