### ISSUE TITLE
Complexidade ciclomática para dicionários

### ISSUE THREAD

**Issue by duarte-lab** [wilsade/WSPack#14]
Para cada linha de um Dictionary, a cálculo da complexidade ciclomática está sendo incrementado de 1.

Segue imagem para exemplificar:
![image](https://user-images.githubusercontent.com/7024493/60202181-6dcc6d00-9820-11e9-95f6-67c460f2ae76.png)

**Comment by wilsade** [comment]
Ok, vamos alterar a regra.
Neste caso, a complexidade seria 2.
Estará disponível na próxima atualização.

**Comment by wilsade** [comment]
Resolvido na versão 3.0.0.26, já disponível na Visual Studio Gallery
