### ISSUE TITLE
Disparar o merge pela history do fonte

### ISSUE THREAD

**Issue by davidcostap** [wilsade/WSPack#16]
Ao acessar a tela de history de um fonte temos os detalhes do changeset. Ao clicar com o botão direito em algum dos changeset poderia ser aberto a tela de buscar changeset com o resultado do mesmo para facilitar o merge ou até mesmo ter um atalho direto para a função merge.
Hoje eu acesse o history, digito o numero do changeset no bloco de notas (não dá para copiar somente o numero), acesso a ferramenta de busca changeset, mando pesquisar o changeset e então clico em merge.

![image](https://user-images.githubusercontent.com/41124735/83258913-827e5700-a18d-11ea-858e-4791622740b2.png)

**Comment by wilsade** [comment]
A sugestão será implementada e estará disponível na próxima Release (3.0.2.x).
Segue tela mostrando como ficará o menu:

![image](https://user-images.githubusercontent.com/14340865/83949405-f659d880-a7f9-11ea-8ad0-7754c3067ebd.png)

**Comment by wilsade** [comment]
Bom dia, David. Segue:

https://github.com/wilsade/WSPack/issues/16

----
William Sade
.NET Developer
Brazil


Em sex., 29 de mai. de 2020 às 09:18, davidcostap <notifications@github.com>
escreveu:

**Comment by wilsade** [comment]
Implementado.
Disponível na versão 3.0.2.24 (ou superior)
