### ISSUE TITLE
Gerar Resource String - Busca do campo valor

### ISSUE THREAD

**Issue by SABFONSECA** [wilsade/WSPack#17]
Se o campo valor tiver plicas a busca não se posiciona num recurso já existente, por exemplo se a string fôr "O valor '{0}' é inválido" não encontra a string nas resources já existentes.
Outra melhoria que acho que seria interessante é quando abre o ecrã de 'Criar Resource String' tentar efetuar a busca do valor nas já existentes e posicionar-se como quando se faz a busca. Até poderia logo assumir a propriedade 'User Resource Existente' se encontra-se a string nas já existentes.

Obrigado

**Comment by wilsade** [comment]
Olá,  bom dia.
Não consegui reproduzir o problema relatado.
Veja abaixo que a ferramenta encontrou a string:

![ValorInvalido](https://user-images.githubusercontent.com/14340865/85139446-cf989a80-b21a-11ea-9f7c-57e35d851fe1.gif)

A string é encontrada e posicionada corretamente.

Sobre a sua sugestão de melhoria para já assumir "Usar resource existente", vou analisar.
Obrigado.

**Comment by SABFONSECA** [comment]
Olá, bom dia,

Penso que já descobri a diferença, no seguinte video reproduzo o problema.
![20200626_130012](https://user-images.githubusercontent.com/18141083/85854909-37b42700-b7ad-11ea-8cab-fabde79aa7de.gif)

Penso que o problema tem a ver também com o campo Nome, o qual eu tenho uma estrutura própria, neste caso o campo Nome é INVALID_VALUE e sem prefixo.

Na abertura se fosse possível efetuar a busca pelo campo valor acho que seria uma boa adicão a esta funcionalidade porque se o campo Nome for alterado ao entrar mesmo que exista uma string igual já não se posiciona.

Obrigado

**Comment by wilsade** [comment]
Olá, boa tarde.
Certo, vamos fazer as duas melhorias que você sugeriu:
1. Melhorar a pesquisa pelo campo valor;
2. Já deixar marcado "Usar resource existente" caso encontre o resource.

Muito obrigado.

**Comment by wilsade** [comment]
Implementado.
Disponível na versão 3.0.2.24 (ou superior)

**Comment by SABFONSECA** [comment]
Muito obrigado. Isto vai melhorar imenso a produtividade desta ferramenta.
