### ISSUE TITLE
Erro ao cadastrar novos Resources

### ISSUE THREAD

**Issue by tkoguta** [wilsade/WSPack#18]
Ao cadastrar uma nova string de resource e começar a digitar o texto no campo "Valor do Resource", um outro Resource é selecionado e o campo "Valor do Resource" é desabilitado, não sendo possível definir o texto do novo Resource.

Visual Studio 2019

**Comment by wilsade** [comment]
Correção feita.
Disponível na versão 3.0.2.28 ou superior.
