### ISSUE TITLE
Ordenação dos Branchs ao Fazer o Merge

### ISSUE THREAD

**Issue by fabitu** [wilsade/WSPack#19]
Sade,
Conforme evidência ao realizar um merge são apresentas as seguintes situações:
1. Não está ordenado pelo branche;
2. Está trazendo branchs já removidas;
![image](https://user-images.githubusercontent.com/25669587/173657167-4fb7b316-e77a-42de-8f62-ec98d1f02a27.png)

**Comment by wilsade** [comment]
Resolvido:

![image](https://user-images.githubusercontent.com/14340865/173657708-a60f7978-59d5-489a-98ca-180d6c074277.png)

Estará disponível na próxima atualização (3.0.8.6, ou superior).
