### ISSUE TITLE
Importação/Exportação de regras/dicionários do summary

### ISSUE THREAD

**Issue by davidcostap** [wilsade/WSPack#3]
Permitir a importação e exportação das regras e dicionários criados para as funcionalidades do summary do WSPack. 
Se possível:
- Permitir selecionar quais regras deseja exportar/importar (além a opção todas)
- Detectar configurações duplicadas e permitir sobrescrever, renomear ou não importar

Está implementação é muito interessante para definição de padrão por equipe ou produto.

**Comment by wilsade** [comment]
Já existe a opção de definir um local para o arquivo de configuração.
Este local pode, inclusive, ser compartilhado com mais de uma pessoa.

Em relação às regras/itens que poderiam ou não ser importados/migrados, qualquer ferramenta de merge tem esta opção.

Estou fechando esta Issue. Caso não concorde, favor reabrir.
Obrigado.
