### ISSUE TITLE
Sugestão de Nome não removeu chaves

### ISSUE THREAD

**Issue by EmersonMiranda** [wilsade/WSPack#4]
Ao utilizar a rotina de Gerar Resources string em um string que possui dados a serem complementados com parâmetros, a sugestão de nome do Resource não removeu as chaves.
Exemplo: 
string.Format("Não é permitido Reiniciar Ordem de Serviço com status {0}", status);

A sugestão de nome ficou NaoPermitidoReiniciarOrdemServicoComStatus{0}

**Comment by wilsade** [comment]
Foi feita a correção e estará disponível a partir da versão:

- 2.0.0.86 (ou superior);

**Comment by wilsade** [comment]
Versão com a correção já disponível.
