### ISSUE TITLE
summary para um campo com atributo

### ISSUE THREAD

**Issue by davidcostap** [wilsade/WSPack#5]
Ao criar um summary para um campo com atributo é apresentando o erro: 
"Tipo ou Membro não encontrado.
Por favor, certifique-se de que o cursor está posicionado na mesma linha do item desejado."
[Summary para atributos.zip](https://github.com/wilsade/WSPack/files/2193598/Summary.para.atributos.zip)

Exemplo de atributo:
[XmlElement(Order = 1)]
  public string pRedBCEfet;

Percebi que o problema ocorre somente em campos, em propriedades o comportamento está correto.
Em anexo a classe onde foi simulado o problemas.
[SchemaNFeV310.zip](https://github.com/wilsade/WSPack/files/2193663/SchemaNFeV310.zip)

**Comment by wilsade** [comment]
Correção feita e disponível na versão:

- 2.0.0.92 (ou superior);
