### ISSUE TITLE
Erro Visual Studio

### ISSUE THREAD

**Issue by snowfake** [wilsade/WSPack#6]
Quando desabitei as opção para não exibir nenhuma informação no código (Fim do bloco) começou a dar erro ao abrir qualquer classe.

**Comment by wilsade** [comment]
Boa tarde.
Foi feita a correção para este caso.
Poderia, por favor, atualizar para a versão:

- 2.0.0.90 (ou superior);

Se o problema voltar a acontecer, favor reabrir esta issue.
Muito obrigado.
