### ISSUE TITLE
Criar uma opção para marcadores dinamicos

### ISSUE THREAD

**Issue by davidcostap** [wilsade/WSPack#9]
Com o novo comportamento dos marcadores é necessário definir qual o número do marcado que está sendo adicionado como por exemplo Crtl + Shift + 1 para o marcador 1. Caso o marcador 1 esteja posicionado em outro ponto ele será redefinido para a nova posição, ficando para o usuário a responsabilidade de consultar os código disponíveis antes de utilizar. 
Solicito uma melhoria para permitir que os marcadores sejam incluídos de forma dinâmica e autoincremental.

**Comment by wilsade** [comment]
Implementado na versão 3.0.0.26, já disponível na Visual Studio Gallery
